backend:
  name: github
  repo: JohnBecerra16/cefin-web
  branch: main
  base_url: https://decap-oauth.vercel.app
  auth_endpoint: auth

media_folder: "public/uploads"
public_folder: "/uploads"

collections:

  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    identifier_field: titulo
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Título", name: "titulo", widget: "string" }

      - { label: "Slug (URL)", name: "slug", widget: "string" }

      - { label: "Fecha", name: "fecha", widget: "datetime" }

      - { label: "Imagen", name: "imagen", widget: "image" }

      - { label: "Descripción", name: "descripcion", widget: "text" }

      - { label: "Contenido", name: "body", widget: "markdown" }


  - name: "eventos"
    label: "Eventos"
    folder: "content/eventos"
    identifier_field: titulo
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Título", name: "titulo", widget: "string" }

      - { label: "Slug (URL)", name: "slug", widget: "string" }

      - { label: "Fecha", name: "fecha", widget: "datetime" }

      - { label: "Lugar", name: "lugar", widget: "string" }

      - { label: "Costo", name: "costo", widget: "string" }

      - { label: "Imagen", name: "imagen", widget: "image" }

      - { label: "Descripción", name: "descripcion", widget: "text" }

      - { label: "Hotmart", name: "hotmart", widget: "string" }

      - { label: "Destacado", name: "destacado", widget: "boolean", default: true }



  - name: "cursos"
    label: "Cursos"
    folder: "content/cursos"
    create: true
    slug: "{{slug}}"

    fields:

      - { label: "ID", name: "id", widget: "number", value_type: "int" }

      - { label: "Título", name: "titulo", widget: "string" }

      - { label: "Slug (URL)", name: "slug", widget: "string" }

      - { label: "Descripción Corta", name: "descripcion", widget: "text" }

      - { label: "Precio", name: "precio", widget: "string" }

      - { label: "Imagen", name: "imagen", widget: "image" }

      - label: "Categoría"
        name: "categoria"
        widget: "select"
        options:
          - fiscal
          - nomina
          - contabilidad

      - { label: "Duración", name: "duracion", widget: "string" }

      - label: "Instructor"
        name: "instructor"
        widget: "select"
        options:
          - Alfredo Cobos
          - Marisol Galvan

      - { label: "Hotmart Link", name: "hotmart", widget: "string" }

      - { label: "Destacado", name: "destacado", widget: "boolean", default: true }

      - { label: "Descripción Larga", name: "body", widget: "markdown" }